[Personal]
source        = maildir:///Users/smit/.local/share/mail
outgoing      = smtp://smitchaudhary10%40gmail.com:APP_PASSWORD@smtp.gmail.com:587
default       = INBOX
from          = Smit Chaudhary <smitchaudhary10@gmail.com>
copy-to       = Sent
cache-headers = true
